[phases.setup]
nixPkgs = ["openssl", "pkg-config"]

[phases.build]
cmds = [
    "cargo build --release", 
    "cp db.json target/release/evertext_bot_rust_db.json", # Backup in build dir
    "cp db.json /app/db.json || true" # Try to put it where we want it
]

[start]
cmd = "./evertext_bot_rust"
